# Generated by Django 5.0.6 on 2024-07-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_options_alter_projects_descripe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(blank=True, choices=[('option 1', 'web'), ('option 2', 'game'), ('option 3', 'Ai'), ('option 3', 'Blockchain')], max_length=50, null=True),
        ),
    ]
