# Generated by Django 5.0.6 on 2024-07-09 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('game', 'game'), ('Ai', 'Ai'), ('Blockchain', 'Blockchain')], max_length=50, null=True),
        ),
    ]
